// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrp_VOin-l-qCdOWtFy5WcxlyMbvk-M4',
    appId: '1:435845874375:web:a6a6396d429420518e34e2',
    messagingSenderId: '435845874375',
    projectId: 'cmsc23-todo-app-ona',
    authDomain: 'cmsc23-todo-app-ona.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-ona.appspot.com',
    measurementId: 'G-YH4T84C860',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUDcu7MpZANEb5l7jceCFHjjgJoEVR5k',
    appId: '1:435845874375:android:5ebfb45eaaa2566e8e34e2',
    messagingSenderId: '435845874375',
    projectId: 'cmsc23-todo-app-ona',
    storageBucket: 'cmsc23-todo-app-ona.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV22HbO9pCLlpAyWLvCy-OY5TUb3hlnug',
    appId: '1:435845874375:ios:1494b4f017abe3818e34e2',
    messagingSenderId: '435845874375',
    projectId: 'cmsc23-todo-app-ona',
    storageBucket: 'cmsc23-todo-app-ona.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV22HbO9pCLlpAyWLvCy-OY5TUb3hlnug',
    appId: '1:435845874375:ios:1494b4f017abe3818e34e2',
    messagingSenderId: '435845874375',
    projectId: 'cmsc23-todo-app-ona',
    storageBucket: 'cmsc23-todo-app-ona.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvrp_VOin-l-qCdOWtFy5WcxlyMbvk-M4',
    appId: '1:435845874375:web:e92035ada718ebf58e34e2',
    messagingSenderId: '435845874375',
    projectId: 'cmsc23-todo-app-ona',
    authDomain: 'cmsc23-todo-app-ona.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-ona.appspot.com',
    measurementId: 'G-YG7PFQYXP2',
  );

}